language: node_js
node_js: "8.8.1"

notifications:
  slack:
    rooms:
      - papercss:1MrmPTVH6FLA95Oa5IfXl7xQ#travis

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - npm install -g npm@5.10.0

install:
  - npm ci

before_script:
    - npm run stylelint
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - fluxbox >/dev/null 2>&1 &
    - chmod +x ./jake.sh
    - chmod +x ./tests/build/scripts/run_jake.sh
    - export DISPLAY=:99.0
    - gulp build

script: "./jake.sh loose=true capture=Firefox"
